// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvosPLDy3p_fSYukjjx3bRi1IlflJnXE',
    appId: '1:447659042482:web:bb372b4db43bdfb6abcbab',
    messagingSenderId: '447659042482',
    projectId: 'storage-dd25a',
    authDomain: 'storage-dd25a.firebaseapp.com',
    storageBucket: 'storage-dd25a.firebasestorage.app',
    measurementId: 'G-ZT5RPFX1C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKf-YmciVSYBdbe2YaqNjIl6ajVgIgniA',
    appId: '1:447659042482:android:4472b9aedb03c03cabcbab',
    messagingSenderId: '447659042482',
    projectId: 'storage-dd25a',
    storageBucket: 'storage-dd25a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0JAbcOhDWfhiYbiVzLckfVu0qwt6Ey_U',
    appId: '1:447659042482:ios:509110b2641baa7dabcbab',
    messagingSenderId: '447659042482',
    projectId: 'storage-dd25a',
    storageBucket: 'storage-dd25a.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0JAbcOhDWfhiYbiVzLckfVu0qwt6Ey_U',
    appId: '1:447659042482:ios:509110b2641baa7dabcbab',
    messagingSenderId: '447659042482',
    projectId: 'storage-dd25a',
    storageBucket: 'storage-dd25a.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsvosPLDy3p_fSYukjjx3bRi1IlflJnXE',
    appId: '1:447659042482:web:fd1ee915fc559578abcbab',
    messagingSenderId: '447659042482',
    projectId: 'storage-dd25a',
    authDomain: 'storage-dd25a.firebaseapp.com',
    storageBucket: 'storage-dd25a.firebasestorage.app',
    measurementId: 'G-SK7KBQB8RB',
  );
}
